### ISSUE TITLE
Sugerencia para centralizar los datos en un repositorio único.

### ISSUE THREAD

**Issue by carranco-sga** [guzmart/covid19_mex#1]
Buenas tardes. 

Antes que nada, muchas gracias por su aportación a la difusión de datos disponibles sobre el coronavirus en el país en un formato más accesible que el que nos ofrece el gobierno. Creo que es fundamental para dimensionar la magnitud del problema y evaluar las políticas públicas que se han efectuado.

Mi nombre es Gabriel Carranco. Soy estudiante de Facultad de Ciencias de la UNAM.  Durante el último par de días he estado compilando y archivando las tablas y comunicados técnicos diarios que ofrece la SSA en [este repositorio](https://github.com/carranco-sga/Mexico-COVID-19). 
Hasta la fecha, ya he terminado de recopilar los casos por estado y tipo de contagio (importado/local), pero me han sugerido incluir tablas diarias de casos como lo ha hecho en este repositorio.
 
Para no duplicar el trabajo (que aparentemente también lo han hecho [aquí](https://serendipia.digital/2020/03/datos-abiertos-sobre-casos-de-coronavirus-covid-19-en-mexico/?unapproved=1624&moderation-hash=71a0582158d0e708291adb9b63d37176#comment-1624)), creo conveniente el centralizar todos los datos que tenemos en algún repositorio que permita a quien lo desee utilizar la información que hemos recopilado, quizá bajo alguna organización en GitHub para poder facilitar aportaciones externas que podamos validar con fuentes oficiales.

Reciba un saludo. Atentamente,
Gabriel Carranco.

**Comment by guzmart** [comment]
Hola Gabriel,
Muchas gracias por tus amables comentarios. Por favor siéntete libre de
vincular las bases de datos que estaré subiendo a un repositorio
centralizado. Por el momento, prefiero modificar personalmente las tablas
dado que estoy en proceso de precisar la fecha en la que se publicaron los
primeros 50 casos. Aprovecho para pedirte que, en caso de contar o
conseguir con los PDFs previos al día 14 de marzo, me sería muy útil si me
los pudieras compartir.
Saludos de codo (por aquello del distanciamiento social),
Katia

**Comment by carranco-sga** [comment]
Gracias por la autorización, será de ayuda. Por desgracia no he encontrado los pdfs los casos entre el 1 de marzo y el 14 de marzo. Para completar mi desglose [por fecha](https://github.com/carranco-sga/Mexico-COVID-19/blob/master/Mexico_COVID19.csv), tuve que recurrir a las conferencias que listo [aquí](https://github.com/carranco-sga/Mexico-COVID-19/blob/master/Documents/Tablas%20casos/Conferencias.md). Los enlaces tienen el timestamp de cuando empiezan a decir o a mostrar información que usé para llenar los huecos.

Saludos (de codo, como debe ser),
Gabriel.
