### ISSUE TITLE
CSVs con un comando

### ISSUE THREAD

**Issue by defvol** [guzmart/covid19_mex#2]
Muchas gracias por compartir estos datos en formato estructurado :tada: !

Seguro una que otra persona vendrá a preguntar por otro tipo de archivo; cada quien tiene su flujo de trabajo. Yo en particular trabajo con CSVs porque se pueden procesar de manera más sencilla.

Pero más que petición quiero aportar aquí, dejando una receta para transformar a CSV con un par de comandos. Y si gustan, puedo abrir un PR con las versiones CSVs o alguna entrada en el README/Wiki explicando como hacerlo. También se podría automatizar la exportación a varios formatos con GitHub actions o un hook.

Hay muchos parsers de XLSX allá fuera, yo opté por instalar [xlsx2csv](https://github.com/dilshod/xlsx2csv) y lo use con `xargs` para agarrar todos los xlsx y pasarlos por esa transformación.

```sh
find . -name '*.xlsx' | xargs -I {} xlsx2csv {} {}.csv
```
_todos los xlsx a csv (se agrega la extensión .csv)_

```sh
find . -name '*.xlsx.csv' | sed 'p;s/\.xlsx\.csv/\.csv/' | xargs -n2 mv
```
_renombra los generados `xlsx.csv` a `.csv`_

De nuevo, gracias por abrir estos datos! Todos odiamos los PDFs.

**Comment by covidctdmx** [comment]
Hola devfvol, en este proyecto se convierten los archivos oficiales en PDF a CSV directamente, los puedes encontrar en el directorio "csv/", https://github.com/covidctdmx/covid_ctd_mx

Saludos, ;D

**Comment by guzmart** [comment]
Hola a ambos.
Debido a que la Secretaría de Salud no incluye una variable que indique fecha de confirmación, convertir el archivo PDF a CSV es bastante acotado: se pierde cualquier tipo de análisis temporal. También aprovecho para comentar que, como menciono en el readme del repo, existen inconsistencias en la forma en la que se agregan casos nuevos por lo que una revisión manual —si el objetivo es hacer un análisis cuidadoso y preciso— es necesaria.

**Comment by defvol** [comment]
> Debido a que la Secretaría de Salud no incluye una variable que indique fecha de confirmación, convertir el archivo PDF a CSV es bastante acotado: se pierde cualquier tipo de análisis temporal.

La transformación sugerida tomaba como base los XLS trabajados en este repositorio.

Pero entiendo tu punto, hay que tener cuidado con la interpretación de los casos publicados por la Secretaría.

Gracias!
