### ISSUE TITLE
Actualizacion de los datos

### ISSUE THREAD

**Issue by mansilla** [guzmart/covid19_mex#3]
Hola, gracias por el repositorio.
Van a seguir actualizando los datos?
Podrias compartir el codigo que usas para parsear los PDFs oficiales?
Saludos y gracias de nuevo por tu trabajo.

**Comment by fazepher** [comment]
Quizás este código pueda funcionar y ayudar sobre todo ahora que los nuevos PDFs confirman más de 100 registros diarios... 

https://github.com/fazepher/covid19_mex/blob/master/02_script/extrae_registros_covid_pdf_ssa_mx.R

@guzmart todavía no hago el pull request porque solo llevo 1 pdf de prueba

**Comment by elzr** [comment]
Hola @mansilla, te recomiendo el excelente trabajo de https://github.com/covidctdmx/covid_ctd_mx/ en terminos de parsear PDFs oficiales a CSV automáticamente. 

Por otra parte, como aquí, yo también estoy haciendo [desde el 14 de marzo](https://twitter.com/elzr/status/1239788323918483456) la chamba manual de fechar los casos y anotar las inconsistencias en una hoja de cálculo de Google: http://bit.ly/covid19mexico

**Comment by mansilla** [comment]
@fazepher @elzr mil gracias. buen trabajo 👍

**Comment by guzmart** [comment]
Hola a todas, 
Una disculpa por los retrasos, intenté automatizar el proceso sin éxito alguno. El día de hoy comenzaré a coordinar un equipo de ~5 personas que se encargaran de hacer las revisiones y correcciones de forma manual fila por fila, pues la SSalud cambia valores en las variables de forma aparentemente arbitraria.
